### ISSUE TITLE
compileJava.dependsOn prep failed

### ISSUE THREAD

**Issue by denny37** [stevesaliman/gradle-properties-plugin#18]
The 'java' plugin has been applied, but it is not compatible with the Android plugins.

**Comment by stevesaliman** [comment]
Can you give me something more to go on here?  What do you mean by "not compatible with Android plugins"?  What is failing?  What error messages are you seeing?

**Comment by stevesaliman** [comment]
I think I know where you're heading with this.

The example in the README file mentions compileJava as an example of how to set up a prep task.  compileJava requires the java plugin, which is not compatible with the android plugin.

The properties plugin does not need the java plugin, nor does it apply it, so you should be able to use it with the android plugin.  The example in the README was meant to show a way you could use it in a Java project.  For android projects, you'd attach the ```prep``` task to a suitable task in the android world.  I've cleaned up the README to hopefully clear up the confusion.
