### ISSUE TITLE
Version 1.5.0 can't be called from plugins portal

### ISSUE THREAD

**Issue by jmeekhof** [stevesaliman/gradle-properties-plugin#31]
It would seem like the released version isn't properly published to the plugins portal. I get an error when I try to use 1.5.0.

```bash
   > Could not find gradle.plugin.net.saliman:gradle-properties-plugin:1.5.0.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/gradle/plugin/net/saliman/gradle-properties-plugin/1.5.0/gradle-properties-plugin-1.5.0.pom
     Required by:
         project : > net.saliman.properties:net.saliman.properties.gradle.plugin:1.5.0

```

The error from the plugins.gradle.org:

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
gradle.plugin.net.saliman/gradle-properties-plugin/1.5.0/ad7420a7a7e38f21b7441600697989d3e8b2557ced225ea3a14698a243c1159c/gradle-properties-plugin-1.5.0.pom
</Key>
<RequestId>2C1D4E51F1081C32</RequestId>
<HostId>
B93ED+kz+tmxhBwOyqT4LSlPdaAI7FUg9IomGg0hNcOJsd9J3m4MWMD1rNkMASwCYaaz27WAXNI=
</HostId>
</Error>
```

**Comment by stevesaliman** [comment]
It would appear that there were some bugs in prior versions of the plugin-publish-plugin, described in https://discuss.gradle.org/t/weird-fail-on-plugins-gradle-org-enunciate-2-10-0/24573.  Following their advice, I republished the plugin using a newer version of plugin-publish-plugin, and version 1.5.1 appears to be found correctly in the Gradle Plugin repository.  It should show up in jcenter and Maven Central shortly.

**Comment by jmeekhof** [comment]
Thanks. I really appreciate your plugin, and am eager to use the new version.
