### ISSUE TITLE
Please tag release 1.5.1

### ISSUE THREAD

**Issue by koppor** [stevesaliman/gradle-properties-plugin#34]
The `CHANGELOG.md` file states that version 1.5.1 is released.

![image](https://user-images.githubusercontent.com/1366654/85143398-fae6ae00-b249-11ea-8079-ebba141eaf05.png)

There is no tag for 1.5.1:

![image](https://user-images.githubusercontent.com/1366654/85143433-0934ca00-b24a-11ea-9adf-5184f851b6d6.png)

**Comment by stevesaliman** [comment]
Thank you for spotting this oversight.  I've created a Release tag for the commit used to publish 1.5.1.
