### ISSUE TITLE
Exception with Gradle 8.x

### ISSUE THREAD

**Issue by jansorg** [stevesaliman/gradle-properties-plugin#44]
After I updated my build from Gradle 7.3.3 to 8.0.2 it started to fail:

```
An exception occurred applying plugin request [id: 'net.saliman.properties', version: '1.5.2']
> Failed to apply plugin 'net.saliman.properties'.
   > Could not create task ':compileKotlin'.
      > Cannot use @TaskAction annotation on method AbstractKotlinCompile.execute() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method
```

Possibly related:
https://youtrack.jetbrains.com/issue/KT-55704/Cannot-use-TaskAction-annotation-on-method-AbstractKotlinCompile.execute-error-while-using-Gradle-8.0-rc-with-KGP-1.5.32

**Comment by stevesaliman** [comment]
I'm not sure what would cause this.  The plugin doesn't use Kotlin, so it shouldn't be including any paricular version of KGP.  It also doesn't  use the TaskAction annotation, as it doesn't create any tasks.

My guess (and it is just a guess) is that something else in your project is causing a mismatch between the version of Kotlin that works with Gradle 8, and the one the build is actually using.

**Comment by jansorg** [comment]
I‘m not sure what‘s causing it, so let‘s close this issue.
